### PR TITLE
fix this

### PR DESCRIPTION
**Pull request by Jerry-ok**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by tadatuta** [comment]
@Jerry-ok, have you faced an error with initial code? Context should be kept in callback automatically. If it's not so it's a bug we should fix in `i-bem.js`.

**Comment by Jerry-ok** [comment]
Ok, I understand, but in example "Uncaught TypeError: this._domEvents.on is not a function" and I change "this._domEvents" to "this.domElem" :(

**Comment by tadatuta** [comment]
You are right, thank you!
Fixed in https://github.com/bem-site/bem-method/commit/e313843b268654ad90a5324b9728a92da97dff8c

**Comment by Jerry-ok** [comment]
thank you :)

**Pull request closed without merging**
